version: '3.8'

services:
  web:
    build: .
    ports:
      - "127.0.0.1:${HOST_PORT:-8000}:8000"
    volumes:
      - ./:/app
    environment:
      - DJANGO_SETTINGS_MODULE=ledmatrix.settings
      - DJANGO_DEBUG=False
    command: >
      sh -c "uv run python manage.py migrate &&
             uv run python manage.py collectstatic --noinput &&
             uv run python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
    user: "1000:1000"