# Generated by Django 5.2.5 on 2025-09-01 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LEDContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_timestamp', models.DateTimeField(blank=True, null=True)),
                ('end_timestamp', models.DateTimeField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_order', models.PositiveIntegerField()),
                ('delay', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('led_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='content.ledcontent')),
            ],
            options={
                'ordering': ['session_order'],
                'unique_together': {('led_content', 'session_order')},
            },
        ),
        migrations.CreateModel(
            name='SessionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('color_r', models.PositiveSmallIntegerField()),
                ('color_g', models.PositiveSmallIntegerField()),
                ('color_b', models.PositiveSmallIntegerField()),
                ('content_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='content.contentsession')),
            ],
        ),
        migrations.CreateModel(
            name='SessionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_index', models.PositiveIntegerField()),
                ('color_r', models.PositiveSmallIntegerField()),
                ('color_g', models.PositiveSmallIntegerField()),
                ('color_b', models.PositiveSmallIntegerField()),
                ('content_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='content.contentsession')),
            ],
            options={
                'unique_together': {('content_session', 'start_index')},
            },
        ),
    ]
