# Generated by Django 5.2.5 on 2025-09-01 15:03

import content.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionline',
            name='color_b',
        ),
        migrations.RemoveField(
            model_name='sessionline',
            name='color_g',
        ),
        migrations.RemoveField(
            model_name='sessionline',
            name='color_r',
        ),
        migrations.RemoveField(
            model_name='sessiontext',
            name='color_b',
        ),
        migrations.RemoveField(
            model_name='sessiontext',
            name='color_g',
        ),
        migrations.RemoveField(
            model_name='sessiontext',
            name='color_r',
        ),
        migrations.AddField(
            model_name='sessionline',
            name='color',
            field=content.fields.ColorField(default='#ffff00', max_length=7),
        ),
        migrations.AddField(
            model_name='sessiontext',
            name='color',
            field=content.fields.ColorField(default='#00ff00', max_length=7),
        ),
    ]
