# Generated by Django 5.2.5 on 2025-09-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_sessionline_color_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsession',
            name='delay',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
