# Generated by Django 5.2.5 on 2025-10-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_contentsession_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsession',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentsession',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
