# Generated by Django 5.2.5 on 2025-10-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_contentsession_end_contentsession_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentsession',
            name='end',
        ),
        migrations.RemoveField(
            model_name='contentsession',
            name='start',
        ),
        migrations.AddField(
            model_name='contentsession',
            name='end_date',
            field=models.DateField(blank=True, help_text='Optional: End date (YYYY-MM-DD)', null=True),
        ),
        migrations.AddField(
            model_name='contentsession',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Optional: End time (hh:mm)', null=True),
        ),
        migrations.AddField(
            model_name='contentsession',
            name='start_date',
            field=models.DateField(blank=True, help_text='Optional: Start date (YYYY-MM-DD)', null=True),
        ),
        migrations.AddField(
            model_name='contentsession',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Optional: Start time (hh:mm)', null=True),
        ),
    ]
