# Generated by Django 5.2.5 on 2025-10-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_contentsession_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledcontent',
            name='end_timestamp',
        ),
        migrations.RemoveField(
            model_name='ledcontent',
            name='start_timestamp',
        ),
        migrations.AddField(
            model_name='ledcontent',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Daily end time (hh:mm)', null=True, verbose_name='Frame0'),
        ),
        migrations.AddField(
            model_name='ledcontent',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Daily start time (hh:mm)', null=True, verbose_name='Frame1'),
        ),
    ]
