# Generated by Django 5.2.5 on 2025-10-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_ledcontent_end_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledcontent',
            name='is_test',
            field=models.BooleanField(default=False, help_text='Mark as test content'),
        ),
    ]
