# Generated by Django 5.2.5 on 2025-12-05 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_ledcontent_is_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Image identifier (a-z, A-Z, 0-9, _, -)', max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SessionAnimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loop_count', models.PositiveIntegerField(default=1, help_text='Number of times to display the animation', verbose_name='Loop Count')),
                ('time_between_images', models.PositiveIntegerField(default=100, help_text='Delay between image changes in milliseconds', verbose_name='Time Between Images (ms)')),
                ('image_names', models.CharField(help_text='Comma-separated image names (e.g., image1,image2,image3)', max_length=500, verbose_name='Image Names')),
                ('content_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='animation', to='content.contentsession')),
            ],
            options={
                'verbose_name': 'Session Animation',
                'verbose_name_plural': 'Session Animations',
            },
        ),
    ]
